name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar Python
        uses: action/setup-python@v5
        with:
          python-version: '3.11'
